name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master  # Substitua pela branch que dispara o deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ASIA3XF7UZAYSIZBPYNX
        aws-secret-access-key: anEANmVQpA8wePVPRyVb1W+1jwXRhQM9VtAT7xsQ
        aws-region: us-east-1

    - name: Zip application
      run: zip -r application.zip .

    - name: Upload to Elastic Beanstalk
      run: |
        aws elasticbeanstalk create-application-version \
          --application-name "glowupbackend" \
          --version-label "v-${{ github.run_id }}" \
          --source-bundle S3Bucket="elasticbeanstalk-us-east-1-805708286001",S3Key="application.zip"
        aws elasticbeanstalk update-environment \
          --application-name "glowupbackend" \
          --environment-name "glowupbackend-prod" \
          --version-label "v-${{ github.run_id }}"
