name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master  # Branch que dispara o deploy (altere para a sua branch principal, se necessário)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Altere para a versão do Node.js que você está usando

    - name: Install dependencies and build project
      run: |
        npm install
        npm run build

    - name: Package and deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        application_name: "glowupbackend"         # Nome da aplicação no Elastic Beanstalk
        environment_name: "glowupbackend-prod"            # Nome do ambiente no Elastic Beanstalk
        aws-access-key-id: ASIA3XF7UZAYSIZBPYNX
        aws-secret-access-key: anEANmVQpA8wePVPRyVb1W+1jwXRhQM9VtAT7xsQ
        version_label: "v${{ github.run_id }}"    # Rótulo da versão do deploy
        region: us-east-1
    - name: Create ZIP file
      run: zip -r backend.zip dist package.json package-lock.json
